# Generated by Django 5.2.2 on 2025-06-20 19:33

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_address_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=bookstore.models.cover_image_upload_to, verbose_name='Обложка'),
        ),
    ]
